{
 "title": "SRE 3",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "95% latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(payment_duration_seconds_bucket[5m])) by (le, bank))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful, Failed, Slow payments per bank",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "payment_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Successful payments percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(payment_requests_total{outcome=\"success\"}[5m])) by (bank) / sum(rate(payment_requests_total[5m])) by (bank)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Amount of requests per bank",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(payment_requests_total) by (bank)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "100 * (1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}